version: '3.8'
services: 
    main:
        build: .
        image: oseghale1/laravel-ecommerce-php8.0_main
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8001:8001
        depends_on: 
            - db

    queue:
        build: .
        image: oseghale1/laravel-ecommerce-php8.0_main
        command: 'php artisan queue:work'
        depends_on: 
            - db        

    db:
        image: mysql:8.0
        environment: 
            DB_CONNECTION: mysql
            DB_HOST: 127.0.0.1
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD:
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306