name: Laravel deployment on AWS elastic beanstalks

on:
  push:
    branches:
      - master 
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      
    - uses: actions/checkout@v3

    - name: Generate deployment packages
      run: zip -r deploy.zip ./

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: giftree-app
        environment_name: Giftree-app-env-3
        version_label: ${{github.sha}}
        existing_bucket_name: elasticbeanstalk-us-east-1-381462137045
        region: us-east-1
        deployment_package: deploy.zip